name: eslint CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        id: tests-workflow
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/eslint/
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/.eslintrc.js') }}

      - name: Install
        run: npm ci

      - name: ESlint Lint
        run: time npm run lint:ci
